### ISSUE TITLE
Resource hint elements have unnecessary </link> closing tag

### ISSUE THREAD

**Issue by skisor** [numical/script-ext-html-webpack-plugin#16]
### Try

```
new ScriptExtHtmlWebpackPlugin({
  preload: {
    test: ...,
    chunks: 'async'
  }
}),
```
### Expected

`<link rel="preload" href="..." as="script">`
### Actual

`<link rel="preload" href="..." as="script"></link>`

_"script-ext-html-webpack-plugin" version: 1.7.1
"html-webpack-plugin": 2.24.1
"webpack": 2.2.1
"node": 6.2.0_

### W3C says:

> In HTML the <link> tag has no end tag.

https://www.w3schools.com/tags/tag_link.asp

**Comment by numical** [comment]
Fixed on v1.7.2

**Comment by lacoe** [comment]
I still receive generated link ending with /> If I change the selfClosingTag to true in resource-hints.js file the generated link is OK.

**Comment by numical** [comment]
HI @lacoe - `selfClosingTag` has been `true` in resource-hints.js since 1.7.2.  What version are you using?

**Comment by xiao-hu** [comment]
I am also seeing the same issue. What even worse, the closing slash causes [html-webpack-pug-plugin](https://github.com/negibouze/html-webpack-pug-plugin) fail to work. For me, the generated links are OK if I change`selfClosingTag` to `false`. I am using version `2.0.1`.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
